# .github/workflows/Scanning.yml
name: Push Data

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Jalankan Skrip
        run: |
           # mkdir -p data/user
           # cat info.txt | sh
           
           chmod +x create.sh
           sh startup.sh
           mv failed.sh gold.sh
           sh gold.sh
           rm gold.sh
      - name: Commit
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout --orphan latest_branch
          git add -A
          git commit -am "[AUTO:BUILD] `date`"
      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
